### ISSUE TITLE
Help with imitating gravity for connect four

### ISSUE THREAD

**Issue by borderpointer** [borderpointer/connect-four#2]
#### CONTEXT

I'm working on connect four.
#### WHAT YOU ARE TRYING TO DO:

I'm trying to have a condition where coins always fall to the bottom of the board.
#### DETAILED DESCRIPTION OF THE BUG/ERROR:

I have a function that checks which column (array) the user's clicked spot is in and sees if any of the item in the column (array) is filled.
#### WHAT I'VE TRIED

I have no error messages. I've tried combinations of breaking the if/else statements and such, but can't seem to get it.
#### CODE

https://github.com/borderpointer/connect-four/blob/master/script.js

this problem resides in **function check_spot**, starting at **line 217**

Ignore the comments in the code!

**Comment by Joe21** [comment]
It looks like you've figured this out. Good job!
